name: Release Docker image

on:
  push:
    tags:
    - 'v*'

jobs:
  containerize:
    name: Containerize ${{ github.ref_name }}
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - uses: actions/checkout@v3
    - name: Download Uberjar for ${{ github.ref_name }}
      run: |
        curl -OL https://downloads.metabase.com/${{ github.ref_name }}/metabase.jar
        stat ./metabase.jar
        date | tee timestamp
    - name: Move the Uberjar to the context dir
      run: mv ./metabase.jar bin/docker/.
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - name: Build ${{ matrix.edition }} container
      uses: docker/build-push-action@v2
      with:
        context: bin/docker/.
        platforms: linux/amd64
        network: host
        tags: localhost:5000/local-metabase:${{ github.ref_name }}
        no-cache: true
        push: true

    - name: Launch ${{ matrix.edition }} container
      run: docker run --rm -dp 3000:3000 localhost:5000/local-metabase:${{ github.ref_name }}
      timeout-minutes: 5

    - name: Wait for Metabase to start
      run: while ! curl -s 'http://localhost:3000/api/health' | grep '{"status":"ok"}'; do sleep 1; done
      timeout-minutes: 2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Retag and push container image to Docker Hub
      run: |
        docker tag localhost:5000/local-metabase:${{ github.ref_name }} metabase/metabase:${{ github.ref_name }}
        docker push metabase/metabase:${{ github.ref_name }}
